### ISSUE TITLE
[Discussion] Consistency (Strong vs Eventual): give a better name

### ISSUE THREAD

**Issue by cottinisimone** [primait/event_sourcing.rs#125]
This discussion is related to [this](https://github.com/primait/event_sourcing.rs/pull/122) PR

**Comment by cottinisimone** [comment]
@emturner proposed this:

```rust
/// Governs the relationship of an event to a resulting projection.
pub enum ParentEventRelationship {
   ///  This projector must succeed, for the parent event to be persisted.
   Blocking,
   /// This projector is allowed to fail, and doesn't block persisting the parent event.
   Fallible
}
```

It seems to me that `ParentEventRelationship` is a bit a too long name. What do you think about renaming it in `Persistence`? This seems to me that is moreover more consistent with `PgStore::persist` function

```rust
/// Specify the persistence for that projector
pub enum Persistence {
    ///  This projector must succeed, for the event to be persisted.
    Mandatory,
    /// This projector is allowed to fail, and doesn't block persisting the event.
    Fallible,
}
```

Or `ProjectorPersistence` too. Anyway no strong opinions on this topic

**Comment by emturner** [comment]
@cottinisimone I agree that the original suggestion is a bit too long!

Fwiw, I like your suggestion of `ProjectorPersistence`, with `Mandatory` & `Fallible`

**Comment by oliverbrowneprima** [comment]
If a projector encounters a failure that it's safe to ignore, can't it simply not return the error? I'm not sure I understand why this is decided at above-the-projector level, rather than the projector deciding for itself whether to propagate errors, and then ESRS treating them as real errors if it does.
