### ISSUE TITLE
[Discussion]: Expose AggregateManager::load potential errors

### ISSUE THREAD

**Issue by fusillicode** [primait/event_sourcing.rs#127]
Hi :smile: 

Sorry as usual for the bother :pray: 
Right now [`AggregateManager::load`](https://github.com/primait/event_sourcing.rs/blob/5a83db12cf3e7a59d38b819d5d38222acfc87e43/src/esrs/aggregate.rs#L120) kind of swallows potential errors that could arise from fetching the saved events. This is done by converting them to an `Option` with `ok?`.

This bitten me a few times in the past thus I'm opening this issue to discuss the potential implications of changing the API of `AggregateManager::load` to return a `Result` instead of an `Option`.

For anything I'm @ your disposal :bow: 

Cheers!

**Comment by cottinisimone** [comment]
But how do you express the fact that there are no events associated to that `aggregate_id`? With a `Result<Option<AggregateState>>`? With a specific error?

**Comment by fusillicode** [comment]
Yep one of the 2 ways. Maybe the 2nd one to avoid a "complex" nested type? 🤔

**Comment by cottinisimone** [comment]
What about remove the `?` from the inner load and panic if an event is not serializable? I think that this should never happen being that that es table should contains only events of that specific type and schema evolution should be always backward compatible..

**Comment by fusillicode** [comment]
> I think that this should never happen being that that es table should contains only events of that specific type and schema evolution should be always backward compatible..

It should not but...it happens...I think that a panic would not be a good option here 😓
