### ISSUE TITLE
AggregateManager::lock_and_load wrong behaviour on empty stream

### ISSUE THREAD

**Issue by angelo-rendina-prima** [primait/event_sourcing.rs#193]
Currently, `lock_and_load` sets a lock in the store then reads the event stream, and returns the aggregate state - together with the lock. While the lock is active (not dropped), the store forbids other read-accesses to the same aggregate instance.

This works fine, expect for the case where there are no events for that aggregate: in this case, `lock_and_load` returns None, and the lock is dropped immediately. This allows for concurrent read-accesses _on an empty stream_.

**Comment by MaeIsBad** [comment]
Opened a card: https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1725/AggregateManagerlockandload-wrong-behaviour-on-empty-stream
