### ISSUE TITLE
an error in a `projector` results in the event not being persisted

### ISSUE THREAD

**Issue by emturner** [primait/event_sourcing.rs#82]
sister issue: #81 

# Problem
see [psql event store](https://github.com/primait/event_sourcing.rs/blob/87583840c501cfbe78ba442750adc0b8928faac0/src/esrs/postgres/mod.rs#L221) and [sqlite event store](https://github.com/primait/event_sourcing.rs/blob/87583840c501cfbe78ba442750adc0b8928faac0/src/esrs/sqlite/mod.rs#L216)

currently, projectors run sequentially within the same transaction as the event is persisted in.  As a result, any single projector failing results in the event failing to be persisted.  An event is also not persisted until all the projectors have been run.  Arguably, the producer of an event (the aggregate/aggregate manager) should not be aware, or have to think about, what the consumers of an event are doing with it.  This is especially true as projectors are potentially able to perform arbitrary side effects (as they should be).

# Possible solution
as with #81 - we could potentially spin off handling/scheduling of projectors into their own tasks.  We could potentially allow projectors to be specified as either strongly, or eventually, constistent.  An aggregate manager/event store could then decide which projectors to spin off entirely, and which ones to wait for before returning.  But crucially, a failing strongly consistent projector should not prevent the aggregate from returning that the event succesfully persisted - so we would need (as we might with #81) a broadcast mechanism.

**Comment by cottinisimone** [comment]
Being that now the full persistence could be customizable i would say that could be enough to add a new function to the projector that the user could use to set consistency level (`strong` or `eventual`). 

We could give a default implementation set to `strong` or leave it entirely to the user. Anyway for the time being i would just change the logic to fail or not depending on consistency level. And i would keep the logic (in default implementation) where the event is not persisted if even one strongly-consistent projector fails.

An example of an implementation could be:

```rust
pub enum Consistency {
    Strong,
    Eventual
}

pub trait Projector<Manager>: Sync
where
    Manager: AggregateManager,
{
    // doc here
    fn consistency() -> Consistency {
        Consistency::Strong
    }

   ...
```

And then if the user need to change the consistency level can override this function setting `Consistency::Eventual`.

WDYT?

**Comment by matteosister** [comment]
I'd really love to do this! And also, at that point, policies will be exactly the same as projectors with eventual consistency right?

**Comment by cottinisimone** [comment]
The problem is always the fact that policy and projector has a different signature. Moreover i think that is better that the policies stays outside of the transaction, or being executed after every `Strong` consistent projector has been successfully executed.
